/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    staff: Staff;
    timeline: Timeline;
    products: Product;
    testimonials: Testimonial;
    articles: Article;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    philosophy: Philosophy;
    'related-company': RelatedCompany;
    overview: Overview;
  };
  globalsSelect: {
    philosophy: PhilosophySelect<false> | PhilosophySelect<true>;
    'related-company': RelatedCompanySelect<false> | RelatedCompanySelect<true>;
    overview: OverviewSelect<false> | OverviewSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  career?: string | null;
  vision?: string | null;
  hobbies?: string | null;
  favoriteWords?: string | null;
  avatar: number | Media;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  year: string;
  month?: string | null;
  title: string;
  detail?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * 小さいほど上に表示されます
   */
  order: number;
  /**
   * ※変更注意。一意な文字を入力してください
   */
  productId: string;
  name: string;
  tagline: string;
  tagline_en?: string | null;
  logo: number | Media;
  logo_long?: (number | null) | Media;
  catchphrase: string;
  description: string;
  image: number | Media;
  mainColor: string;
  subColor: string;
  /**
   * トップページ等のアニメーション演出を選択します
   */
  animation?: ('miru' | 'kiku' | 'ageru') | null;
  about: {
    main: {
      heading_jp: string;
      heading_en?: string | null;
      text: string;
    };
    process: {
      title_jp: string;
      title_en?: string | null;
      steps?:
        | {
            title_jp: string;
            title_en?: string | null;
            description: string;
            id?: string | null;
          }[]
        | null;
    };
    features: {
      title_jp: string;
      title_en?: string | null;
      items?:
        | {
            title_jp: string;
            title_en?: string | null;
            description: string;
            image: number | Media;
            id?: string | null;
          }[]
        | null;
    };
    cta: {
      title_jp: string;
      title_en?: string | null;
      description: string;
      buttonText: string;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  date: string;
  quote: string;
  name: string;
  title: string;
  company: string;
  logo?: (number | null) | Media;
  avatar?: (number | null) | Media;
  products: ('LOOK' | 'PROBE' | 'BOON')[];
  linkType?: ('internal' | 'external') | null;
  externalLink?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  isTopDisplay?: boolean | null;
  category: 'column' | 'exhibition' | 'product_info';
  date: string;
  image?: (number | null) | Media;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  excerpt: string;
  linkType?: ('internal' | 'external') | null;
  externalLink?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * サイト管理用ユーザーアカウント
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 管理者以外変更できません
   */
  role: 'admin' | 'editor';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'timeline';
        value: number | Timeline;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  career?: T;
  vision?: T;
  hobbies?: T;
  favoriteWords?: T;
  avatar?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  year?: T;
  month?: T;
  title?: T;
  detail?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  order?: T;
  productId?: T;
  name?: T;
  tagline?: T;
  tagline_en?: T;
  logo?: T;
  logo_long?: T;
  catchphrase?: T;
  description?: T;
  image?: T;
  mainColor?: T;
  subColor?: T;
  animation?: T;
  about?:
    | T
    | {
        main?:
          | T
          | {
              heading_jp?: T;
              heading_en?: T;
              text?: T;
            };
        process?:
          | T
          | {
              title_jp?: T;
              title_en?: T;
              steps?:
                | T
                | {
                    title_jp?: T;
                    title_en?: T;
                    description?: T;
                    id?: T;
                  };
            };
        features?:
          | T
          | {
              title_jp?: T;
              title_en?: T;
              items?:
                | T
                | {
                    title_jp?: T;
                    title_en?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
            };
        cta?:
          | T
          | {
              title_jp?: T;
              title_en?: T;
              description?: T;
              buttonText?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  date?: T;
  quote?: T;
  name?: T;
  title?: T;
  company?: T;
  logo?: T;
  avatar?: T;
  products?: T;
  linkType?: T;
  externalLink?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isTopDisplay?: T;
  category?: T;
  date?: T;
  image?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  excerpt?: T;
  linkType?: T;
  externalLink?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "philosophy".
 */
export interface Philosophy {
  id: number;
  vision: {
    tagline: string;
    lead: string;
  };
  representatives?:
    | {
        name: string;
        title: string;
        avatar: number | Media;
        greeting: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "related-company".
 */
export interface RelatedCompany {
  id: number;
  name: string;
  logo: number | Media;
  url: string;
  description?: string | null;
  established?: string | null;
  capital?: string | null;
  motto?: string | null;
  employees?: string | null;
  bases?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  businesses?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  offices?:
    | {
        label: string;
        address: string;
        tel?: string | null;
        fax?: string | null;
        mapEmbedUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "overview".
 */
export interface Overview {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    mainLogo?: (number | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryHref?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryHref?: string | null;
  };
  /**
   * 組織の課題を示すキーワードを自由に追加・編集できます。
   */
  issueKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  clientLogos?:
    | {
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  strengths?:
    | {
        /**
         * 一覧ページのアイコンに使用されます。
         */
        icon:
          | 'users'
          | 'target'
          | 'trendingUp'
          | 'barChart2'
          | 'layers'
          | 'zap'
          | 'brainCircuit'
          | 'headphones'
          | 'playCircle'
          | 'briefcase';
        badge?: string | null;
        title: string;
        description: string;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "philosophy_select".
 */
export interface PhilosophySelect<T extends boolean = true> {
  vision?:
    | T
    | {
        tagline?: T;
        lead?: T;
      };
  representatives?:
    | T
    | {
        name?: T;
        title?: T;
        avatar?: T;
        greeting?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "related-company_select".
 */
export interface RelatedCompanySelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  description?: T;
  established?: T;
  capital?: T;
  motto?: T;
  employees?: T;
  bases?:
    | T
    | {
        name?: T;
        id?: T;
      };
  businesses?:
    | T
    | {
        name?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        label?: T;
        address?: T;
        tel?: T;
        fax?: T;
        mapEmbedUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "overview_select".
 */
export interface OverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        mainLogo?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryHref?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryHref?: T;
      };
  issueKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  clientLogos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        icon?: T;
        badge?: T;
        title?: T;
        description?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}